### ISSUE TITLE
Dumb question re secret?

### ISSUE THREAD

**Issue by ghenry** [gryphonshafer/Auth-GoogleAuth#2]
Hi Gryphon,

I'm presuming the `secret` is to be saved specific to that user? It's shared just between the backend and the `key_id` not a secret to be used for every user?

Just the docs are:

```
secret

This can be any string. It'll be used as the internal secret key to create the QR codes and authentication codes.
```

and that says "QR codes".

I suppose there's no harm in doing it per user in their profile as it were. Use case is 2FA for a web app login, so once passed user/password login, a check it run to see if 2FA is enabled, then retrieve secret and present code prompt via Google Authenticator App.

Thanks.

**Comment by ghenry** [comment]
Looks like the secret is in the generated URL, so best have it unique per user. Thanks.

**Comment by gryphonshafer** [comment]
Not a dumb question at all. `secret` is like a salt for the encryption. You can implement it in a variety of ways, but I strongly recommend a unique `secret` per user. It gets used to generated the QR code, which is how `secret` is shared with the user. And it's this shared `secret` that let's both sides generate time-sensitive access codes.
