### ISSUE TITLE
Design pattern for "Backup codes"

### ISSUE THREAD

**Issue by ghenry** [gryphonshafer/Auth-GoogleAuth#3]
Hi Gryphon,

I'm presuming this is out of scope for your library, but I see this every where in 2FA implementations, but not in others. There does seem to be a common way to do it. Is this something you have done yourself or can point to the relevant RFC section? 

Thanks for your lib and time,
Gavin.

**Comment by gryphonshafer** [comment]
Yes, this would be out of scope for 2FA TBOT. Backup codes designs seem to me like they're platform-specific. Practically speaking, I don't think they're much different than the user backing up his or her own TBOT secret.
